### ISSUE TITLE
Holiday appears as selected when Auto-populate is turned on

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/woocommerce-delivery-date#101] opened 2018-01-24 11:16 UTC
I have entered 26th January as a holiday. In auto-populate, that's the first available date. It appears as selected in the delivery date field.
Holiday shouldn't appear selected.

**Comment by komal-maru** [comment] 2018-06-28 13:36
Reference fix: 54dc62d274706d472d9d4ac09a2ba5c47d0377cb

After this fix, the issue is not replicated. hence closing with the reference fix

**Comment by Dhara61** [comment] 2019-03-25 11:14
This issue is still replicated. 

I have set Wednesday as a delivery date and 27th March is set as a holiday then also the first available date is 27th March. Auto-populate is on. 

Worst is I am able to place an order for 27th March that is a holiday. 

Screenshots: http://prntscr.com/n2lbrl , http://prntscr.com/n2lbzb , http://prntscr.com/n2lc8l , http://prntscr.com/n2lcxf

**Comment by apeksha10** [comment] 2019-04-04 05:12
With the latest git copy, I am able to replicate this issue

screenshot of settings : https://www.screencast.com/t/MJ0qHBQ9w
https://www.screencast.com/t/ygkMgk8E8yD1

**Comment by apeksha10** [comment] 2019-04-04 08:12
Some hooks present on my local hence above issue replicate
After committing that hook, no more issue replicate

hence closed issue

**Closed by apeksha10** 2019-04-04 08:12 UTC
Labels: bug
