### ISSUE TITLE
Issue with auto-populate not considering non-working days

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/woocommerce-delivery-date#115] opened 2018-04-14 06:05 UTC
Weekdays: Wednesday
Min Delivery Time: 103
Number of dates to choose: 30
Auto-populate: on
Apply Minimum Delivery Time for non working weekdays: on

With above settings, the calendar shows the date of the following month instead of current month, despite 2 dates being available in current month. The calendar should show the first date from the current month & not following month.

**Comment by apeksha10** [comment] 2018-04-23 06:02
Still..wrong delivery date shown on checkout page
See the settings screenshot https://www.screencast.com/t/W9VdbYCh
https://www.screencast.com/t/uMj8AxcuFSME

Checkout page screenshot : https://www.screencast.com/t/hl9QM6ZuAhYZ
https://www.screencast.com/t/q2h8qol8Kjs

Checkout page shows 2 May 2018 is first available delivery date
Hence  re-open this issue

**Comment by komal-maru** [comment] 2018-06-28 13:49
Reference fix: 54dc62d

After this fix(#101), the issue is not replicated. Hence closing with the reference fix

**Closed by komal-maru** 2018-06-28 13:49 UTC
Labels: Auto-populate, Minor, bug
