### ISSUE TITLE
Lockout date after X orders is not working with more than quantity order placed. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#73] opened 2017-07-05 10:18 UTC
Here Lockout date after X orders set as 5 and i placed the order for 10 qty so the order is placed which is wrong.

Screenshot of setting page: https://www.screencast.com/t/27yYZt36ia
Screenshot of Order received page: https://www.screencast.com/t/eOFt0Rnee8t

**Comment by komal-maru** [comment] 2018-01-20 06:45
We do not have the feature where the delivery date will be booked based on the quantities in the Lite version. In Lite version, the lockout only works with orders and not with quantities.

Hence the issue is marked as Invalid and closing it.

**Closed by komal-maru** 2018-01-20 06:45 UTC
Labels: Major, bug, invalid

**Comment by ashokrane** [comment] 2018-01-24 11:51
Nothing to test here. Marking as Fixed.
